# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='album',
            new_name='alb',
        ),
        migrations.AlterField(
            model_name='archivos',
            name='artista',
            field=models.CharField(max_length=120),
        ),
    ]
