# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20161027_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='archivo',
            new_name='cancion',
        ),
    ]
